# 🧮 Part 1: Linear Algebra Basics
Welcome to the child-friendly introduction to Linear Algebra for Data Science! Let's learn with simple words and practical examples.

## 📌 What is a Vector?
A vector is like a direction on a treasure map. It tells you how far to go in each direction.

Example: [3, 4] means 3 steps right, 4 steps up.


In [1]:
import numpy as np


# Define a vector
vector = np.array([1,2,3,4,5])
print("Vector:", vector)

Vector: [1 2 3 4 5]


## ➕ Vector Operations
You can add, subtract, or multiply vectors by a number.

In [7]:
vector1 = np.array([1,2])
vector2 = np.array([3,4])

# Addition
vector1 + vector2
# Multiplication
vector1 * vector2
# Substraction
vector1 - vector2
# Division
vector1 / vector2

array([1, 2])

In [8]:
# Scalar multiplication
2 * vector1

array([2, 4])

## 🔸 Dot Product
It shows how similar two vectors are. If the result is large, they point in similar directions.

- Formula: Multiply the numbers and add them.
`→ [1, 2] • [3, 4] = (1×3) + (2×4) = 3 + 8 = 11`

In [10]:
# Dot Product
dot_product = np.dot(vector1, vector2)
dot_product

np.int64(11)

## 📏 Vector Norm (Length of a Vector)
The norm tells us how long a vector is — like the length of a rope.

- L2 Norm: The regular straight-line length.
`→ For [3, 4], it’s √(3² + 4²) = √25 = 5`

In [11]:
# Vector Norm
vector3 = np.array([1,2,3])
length = np.linalg.norm(vector3)
length

np.float64(3.7416573867739413)

## 📏 Extra: L3 Norm (Third Order Norm)

The **L3 norm** is another way to measure the length of a vector, like L2 norm, but instead of squaring the numbers, it **cubes** them.

### 🧮 Formula:
$$
L_3 = \left( \sum |x_i|^3 \right)^{1/3}
$$

This means we:
- Take the absolute value of each number
- Raise it to the power of 3
- Add them all together
- Then take the cube root of the result


In [13]:
# L3 Norm (Manually)
def l3_norm(v):
    return np.sum(np.abs(v)**3)**(1/3)

print("L3 Norm of [1,2,3]:", l3_norm(vector3))

L3 Norm of [1,2,3]: 3.3019272488946263


## 🧾 What is a Matrix?
A matrix is a table of numbers (like an Excel sheet).

Example:
```
[ [1, 2],
  [3, 4] ]
```

In [14]:
# Define a matrix
matrix = np.array([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

Matrix:
 [[1 2]
 [3 4]]


## ⚙️ Matrix Operations
You can add, multiply, or transpose a matrix.

In [16]:
# Transpose

transpose = matrix.T
print("Transpose : \n", transpose)

Transpose : 
 [[1 3]
 [2 4]]


In [19]:
# Matrix multiplication
multiplied = np.dot(matrix, transpose)
print("Matrix × Transpose:\n", multiplied)

Matrix × Transpose:
 [[ 5 11]
 [11 25]]


## 🔄 Inverse and Determinant
The **inverse** is like undoing the effect of the matrix. The **determinant** helps us know if an inverse exists.


In [22]:
# Determinant and Inverse
from numpy.linalg import det, inv

# Calculate determinant
determinant = det(matrix)
print("Determinant:", determinant)

# Calculate inverse (if determinant is not zero)
if determinant != 0:
    inverse = inv(matrix)
    print("Inverse:\n", inverse)
else:
    print("Inverse does not exist.")

Determinant: -2.0
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## 🔍 Eigenvalues and Eigenvectors
These are special values and directions that help in data reduction (like PCA).

In [23]:
# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## ✅ Where We Use This in Data Science
- Data tables are stored as matrices
- PCA uses eigenvalues to reduce columns
- Neural networks use vectors and matrices to learn

Great job! 🎉 You’ve finished Part 1 of your Data Science Math Journey!
