## 🧠 What is NumPy?

Think of **NumPy** as a **super calculator for Python**. 🧮  
It helps you store and play with numbers **very fast** — especially in **rows and columns**, like a table or a grid.

We use it mostly when we want to do **math with big sets of numbers**, such as:
- 🎮 Data in a game  
- 🌦️ Weather readings  
- 🔬 Science experiments  

It's one of the most important libraries in **Data Science and Machine Learning**.


## 📦 Installing and Upgrading NumPy

You can install or upgrade **NumPy** using `pip`, which is Python's package manager.

### ✅ To Install NumPy:
```bash 
pip install numpy
```

### ✅ To update, run::
```bash 
pip install --upgrade numpy
```

In [1]:
# !pip install numpy

## ✅ To Check the Installed Version:

You can check your NumPy version using Python code:

In [2]:
import numpy as np
np.__version__

'2.2.4'

### ✅ NumPy Array — Like a Magic List ✨

A **NumPy array** is like a **list in Python**, but it's **faster, takes less memory,** and you can do **math on all its items at once** — just like magic! 🎩✨

In [3]:
# Imagine you have a list of numbers like this:
nums = [1,2,3,4,5]

# This is a normal Python list. But what if you want to multiply all numbers by 2?
# With a regular list, you need a loop:
new_list = [num * 2 for num in nums]
# new_list

# But with NumPy, you can do it in one go using a NumPy array:
arr = np.array(nums)

new_arr = arr * 2
# new_arr

That’s the power of **NumPy arrays**:

- Fast  
- Clean  
- Works like math in real life


# 🧮 NumPy Arrays vs Python Lists:

| Feature            | Python List | NumPy Array       |
| ------------------ | ----------- | ----------------- |
| Speed              | Slow        | Very Fast ⚡       |
| Memory Usage       | More        | Less 🧠           |
| Math Operations    | Need loops  | Done directly ➕✖️ |
| Supports Multidim? | Not easily  | Yes, like grids!  |


## 📦 1. Creating a NumPy Array 
### ✅ From a list

In [4]:
nums_arr = np.array([1,2,3,4,5])
nums_arr

array([1, 2, 3, 4, 5])

## 🧱 2. Types of Arrays

### 1D Array – A simple line of numbers

In [5]:
arr1 = np.array([10, 20, 30])
arr1

array([10, 20, 30])

### 2D Array – Like a table or matrix

In [6]:
arr2 = np.array([[1, 2], [3, 4]])
arr2

array([[1, 2],
       [3, 4]])

### 3D Array – A cube of numbers

In [7]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## 🔍 3. Array Attributes

Let's learn about the **secret info** each array has:

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
# Number of dimensions
arr.ndim

2

In [10]:
# Rows and columns (rows, cols)
arr.shape

(2, 3)

In [11]:
# Total number of elements
arr.size

6

In [12]:
# Data type of array elements
arr.dtype

dtype('int64')

In [13]:
# Memory used per item (bytes)
arr.itemsize

8

In [14]:
# Total memory used by array
arr.nbytes # arr.itemsize * arr.size

48

## 🧮 4. Array Operations (Like Magic on All Elements)
You can do math directly:

In [15]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1,2],[3,4]])
add3 = arr + 3
add3

mul2 = arr2 * 2
mul2

# You can do math between arrays too:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x + y  # [5 7 9]


array([5, 7, 9])

## 🔁 5. Array Indexing and Slicing

## Indexing
Access single item:

In [16]:
#  1D Array 
a1 = np.array([10, 20, 30, 40])
a1[2]  # 30

# 2D array
a2 = np.array([[1,2],[3,4]])
a2[0][1]

# 3D array
a3 = np.array([[[1,2],[3,4],[5,6]]])
a3[0][0][1]

np.int64(2)

## Slicing

In [17]:
# 1D Array Slicing
# | ---------- | ------------------ | --------------- |
# | Slice      | Meaning            | Output          |
# | ---------- | ------------------ | --------------- |
# | `a1[2]`    | Element at index 2 | `30`            |
# | `a1[1:3]`  | From index 1 to 2  | `[20 30]`       |
# | `a1[:2]`   | First 2 elements   | `[10 20]`       |
# | `a1[::2]`  | Every 2nd element  | `[10 30]`       |
# | `a1[::-1]` | Reversed array     | `[40 30 20 10]` |
# | ---------- | ------------------ | --------------- |

# 2D Array Slicing
# | ---------- | --------------------------- | ---------------- |
# | Slice      | Meaning                     | Output           |
# | ---------- | --------------------------- | ---------------- |
# | `a2[0][1]` | Row 0, column 1             | `2`              |
# | `a2[0, 1]` | Same as above, better style | `2`              |
# | `a2[1, :]` | Second row                  | `[3 4]`          |
# | `a2[:, 0]` | First column                | `[1 3]`          |
# | `a2[:, :]` | Entire array                | `[[1 2], [3 4]]` |
# | ---------- | --------------------------- | ---------------- |

# 3D Array Slicing
# Structure:
# 1 block
# 3 rows
# 2 columns
# | ------------- | ------------------------------ | ------------------------- |
# | Slice         | Meaning                        | Output                    |
# | ------------- | ------------------------------ | ------------------------- |
# | `a3[0][0][1]` | Block 0, Row 0, Column 1       | `2`                       |
# | `a3[0, 1, 0]` | Block 0, Row 1, Column 0       | `3`                       |
# | `a3[:, 1, :]` | All blocks, Row 1, all columns | `[[3 4]]`                 |
# | `a3[:, :, 1]` | All blocks, all rows, column 1 | `[[2 4 6]]`               |
# | `a3[:, :, :]` | Entire 3D array                | `[[[1 2], [3 4], [5 6]]]` |
# | ------------- | ------------------------------ | ------------------------- |

## 🎨 6. Useful Array Functions

### 📌 1. Array Creation

In [18]:
# np.array()	- Creates an array from list/tuple
arr1 = np.array([1,2,3,4,5])
# arr1

# np.arange()	- Range with step
arr2 = np.arange(0, 10, 2)
# arr2

# np.linspace()	- Evenly spaced numbers in interval
arr3 = np.linspace(0, 1, 5)
# arr3

# np.zeros()	- Array filled with zeros
arr4 = np.zeros((2,5))
# arr4

# np.ones()	 - Array filled with ones
arr5 = np.ones((2,2))
# arr5

# np.full() - Array filled with specific value
arr6 = np.full((2,2), 3.14)
# arr6

# np.eye()	- Identity matrix
arr7 = np.eye(5)
# arr7

# np.random.rand()	- Random numbers (uniform) - 0 ≤ value < 1
arr8 = np.random.rand(2,3) 
# arr8

# np.random.randint()	- Random integers - np.random.randint(low, high=None, size=None)
arr9 = np.random.randint(10, 20, (5,3))
# arr9

### 🔄 2. Array Manipulation

In [19]:
# reshape()	 - Change shape of array
arr10 = np.array([1,2,3,4,5,6])
arr10_ = arr10.reshape(2,3)
# arr10_

# flatten()	 - Convert to 1D
arr11 = np.array([1,2,3,4,5,6])
arr11_ = arr11.flatten()
# arr11_

# transpose() / T	- Transpose rows ↔ columns
arr_t = arr10_.transpose()
# arr_t

# concatenate()	 - Join arrays along an axis
arr12 = np.array([1,2,3,4,5,6])
arr13 = np.array([1,2,3,4,5,6])
arr_cat = np.concatenate([arr12, arr13])
# arr_cat

# stack() / vstack() / hstack()	 - Stack arrays vertically/horizontally
# stack = np.stack([arr12, arr13])
# stack
vstack = np.vstack([arr12, arr13])
# vstack
hstack = np.hstack([arr12, arr13])
# hstack

# split() / hsplit() / vsplit()	 - Split arrays
# ❗ Important:
# - split() works on any dimension but needs equal sizes.
# - hsplit() = split horizontally (columns).
# - vsplit() = split vertically (rows).

split = np.split(arr12, 2)
# split
arr14 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
hsplit = np.hsplit(arr14, 2)
# hsplit
arr15 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
vsplit = np.vsplit(arr15, 2)
# vsplit

# expand_dims()	- Add new axis
arr16 = np.array([1, 2, 3])  # Shape: (3,)
expanded = np.expand_dims(arr16, axis=0)  # Add new axis at position 0
# expanded.shape
# expanded
# expanded.ndim

# squeeze()	 - Remove single-dimensional entries
arr17 = np.array([[[1, 2, 3]]])  # Shape: (1, 1, 3)
# print("Original shape:", arr17.shape)
# print(arr17)
# print(arr17.ndim)

squeezed = np.squeeze(arr17)
# print("Squeezed shape:", squeezed.shape)
# print(squeezed)
# print(squeezed.ndim)

## 🔢 3. Mathematical Operations

| Function         | Description            | Example              |
|------------------|------------------------|----------------------|
| `np.add()`       | Element-wise addition  | `np.add(a, b)`       |
| `np.subtract()`  | Subtraction            | `np.subtract(a, b)`  |
| `np.multiply()`  | Multiplication         | `np.multiply(a, b)`  |
| `np.divide()`    | Division               | `np.divide(a, b)`    |
| `np.dot()`       | dot product            | `np.dot(a, b)`       |
| `np.power()`     | Exponentiation         | `np.power(a, 2)`     |
| `np.mod()`       | Modulus                | `np.mod(a, b)`       |
| `np.sqrt()`      | Square root            | `np.sqrt(a)`         |
| `np.exp()`       | Exponential (e^x)      | `np.exp(a)`          |
| `np.log()`       | Natural logarithm (ln) | `np.log(a)`          |


## 📊 4. Statistical Functions

| Function        | Description            | Example            | Explanation                                                                 |
|----------------|------------------------|--------------------|-----------------------------------------------------------------------------|
| `np.mean()`     | Mean / Average         | `np.mean(a)`       | Adds all elements and divides by the number of elements.                    |
| `np.median()`   | Median value           | `np.median(a)`     | The middle value of a sorted list. If even elements, average of two middles.|
| `np.std()`      | Standard Deviation     | `np.std(a)`        | Shows how much values deviate from the mean.                               |
| `np.var()`      | Variance               | `np.var(a)`        | Square of the standard deviation. Shows data spread.                        |
| `np.min()`      | Minimum value          | `np.min(a)`        | Returns the smallest number in the array.                                   |
| `np.max()`      | Maximum value          | `np.max(a)`        | Returns the largest number in the array.                                    |
| `np.sum()`      | Sum of elements        | `np.sum(a)`        | Adds all the elements in the array.                                         |
| `np.argmin()`   | Index of min value     | `np.argmin(a)`     | Returns the index (position) of the smallest value in the array.            |
| `np.argmax()`   | Index of max value     | `np.argmax(a)`     | Returns the index (position) of the largest value in the array.             |


## 5. Array Testing / Checking

| Function        | Description                     | Example             | Explanation                                                                 |
|----------------|----------------------------------|---------------------|-----------------------------------------------------------------------------|
| `np.all()`      | Are **all** elements `True`?     | `np.all(a > 0)`     | Returns `True` only if **every** element satisfies the condition.          |
| `np.any()`      | Is **any** element `True`?       | `np.any(a < 0)`     | Returns `True` if **at least one** element satisfies the condition.        |
| `np.isnan()`    | Check for `NaN` values           | `np.isnan(a)`       | Returns a boolean array where `True` marks a `NaN` (Not a Number).         |
| `np.isinf()`    | Check for `inf` (infinity)       | `np.isinf(a)`       | Returns a boolean array where `True` marks positive or negative infinity.  |
| `np.where()`    | Indices where condition is `True`| `np.where(a > 5)`   | Returns indices where the condition is met. Useful for conditional filtering.|
| `np.unique()`   | Return unique elements           | `np.unique(a)`      | Returns sorted array of unique elements from the input.                    |


## 🎯 What is a Scalar?
A **scalar** is a single numerical value, like `5`, `3.14`, or `-2`.

NumPy supports **element-wise operations** between an array and a scalar.

In [20]:
a = np.array([1, 2, 3, 4])

print(a + 2)   # [3 4 5 6]
print(a * 3)   # [3 6 9 12]
print(a - 1)   # [0 1 2 3]
print(a / 2)   # [0.5 1.  1.5 2. ]

[3 4 5 6]
[ 3  6  9 12]
[0 1 2 3]
[0.5 1.  1.5 2. ]


## 🎯 What is a Vector?
A **vector** is a 1D NumPy array — a list of numbers with direction, like `[1, 2, 3]`.

NumPy also supports **element-wise vector operations** (arrays of the same shape):

In [21]:
b = np.array([10, 20, 30, 40])

print(a + b)   # [11 22 33 44]
print(a * b)   # [10 40 90 160]
print(a - b)   # [-9 -18 -27 -36]

[11 22 33 44]
[ 10  40  90 160]
[ -9 -18 -27 -36]


## ✅ np.dot(a, b) → Dot Product
## 👉 What is the dot product?
The dot product of two vectors is:

`a⋅b=(1×4)+(2×5)+(3×6)=4+10+18=32`

## ✅ np.linalg.norm(a) → Vector Magnitude (Length)
## 👉 What is a norm?
The Euclidean norm (or magnitude) of a vector a = [1, 2, 3] is:

`∥a∥ = √(1² + 2² + 3²) = √14 ≈ 3.741`

## ✅ Logarithmic Functions

**Purpose**: Used to calculate logarithms — useful in mathematics, statistics, machine learning, and data transformation.

| Function       | Description                        | Example         |
|----------------|------------------------------------|-----------------|
| `np.log(x)`    | Natural logarithm (base **e**)     | `np.log(x)`     |
| `np.log10(x)`  | Logarithm base **10**              | `np.log10(x)`   |
| `np.log2(x)`   | Logarithm base **2**               | `np.log2(x)`    |


In [22]:
x = np.array([1, np.e, 10])

print(np.log(x))
print(np.log10(x))    
print(np.log2(x))     

[0.         1.         2.30258509]
[0.         0.43429448 1.        ]
[0.         1.44269504 3.32192809]


Note: Input values must be positive, else you'll get nan or error.

## ✅ Exponential Function

**Purpose**: Raises **e** (Euler’s number ≈ 2.718) to the power of each element in the array.  
Commonly used in exponential growth, probability distributions, and machine learning.

| Function     | Description                        | Example       |
|--------------|------------------------------------|---------------|
| `np.exp(x)`  | Calculates **e^x** for each element| `np.exp(x)`   |


In [23]:
x = np.array([0, 1, 2])

print(np.exp(x)) 

[1.         2.71828183 7.3890561 ]


## ✅ Trigonometric Functions

**Purpose**: Used for calculating trigonometric values of angles in **radians**.  
Useful in geometry, signal processing, physics, and machine learning.

| Function     | Description             | Example       |
|--------------|-------------------------|---------------|
| `np.sin(x)`  | Sine of angle `x`       | `np.sin(x)`   |
| `np.cos(x)`  | Cosine of angle `x`     | `np.cos(x)`   |
| `np.tan(x)`  | Tangent of angle `x`    | `np.tan(x)`   |


In [24]:
x = np.array([0, np.pi/2, np.pi])

print(np.sin(x))      # [0. 1. 0.]
print(np.cos(x))      # [1. 0. -1.]
print(np.tan(x))      # [0. very large ~∞ 0.]

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


### Convert Degrees to Radians:

In [25]:
np.radians(180)       # Output: 3.14159265 (π)

np.float64(3.141592653589793)

## ✅ Ceil and Floor Functions

**Purpose**: Rounds numbers **up** (`ceil`) or **down** (`floor`) to the nearest integer.  
Useful in numerical processing, rounding strategies, and control systems.

| Function       | Description                             | Example         |
|----------------|-----------------------------------------|-----------------|
| `np.ceil(x)`   | Rounds **UP** to the next highest integer | `np.ceil(x)`    |
| `np.floor(x)`  | Rounds **DOWN** to the next lowest integer| `np.floor(x)`   |


In [26]:
x = np.array([1.2, 2.5, 3.9])

print(np.ceil(x))     # [2. 3. 4.]
print(np.floor(x))    # [1. 2. 3.]

[2. 3. 4.]
[1. 2. 3.]
