# 🧠 Session 15: NumPy Tricks

In this session, we will explore some cool and useful **NumPy tricks** to work smarter with arrays.

---

## ✅ Topics Covered

1. `np.sort()` – Sorting arrays  
2. `np.append()` – Adding elements to an array  
3. `np.concatenate()` – Joining arrays  
4. `np.percentile()` – Getting percentiles  
5. `np.flip()` – Reversing array contents  
6. Set Operations in NumPy:
    - `np.unique()`  
    - `np.intersect1d()`  
    - `np.union1d()`  
    - `np.setdiff1d()`  
    - `np.setxor1d()`  

---

In [2]:
import numpy as np

## 1️⃣ np.sort() – Sorting Arrays

In [3]:
a = np.array([3, 1, 5, 2])
sorted_a = np.sort(a)
print("Sorted array:", sorted_a)

Sorted array: [1 2 3 5]


## 2️⃣ np.append() – Adding Elements

In [4]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5])
print("Appended array:", b)

Appended array: [1 2 3 4 5]


---

## 3️⃣ `np.concatenate()` – Joining Arrays

### 🔹 np.concatenate()

Combines two or more arrays.


In [8]:
a = np.array([1, 2])
b = np.array([3, 4])

result = np.concatenate((a, b))
print(result)  # [1 2 3 4]

[1 2 3 4]


## 4️⃣ np.percentile() – Get Percentile

In [10]:
data = np.array([10, 20, 30, 40, 50])
p = np.percentile(data, 25)
print("50th Percentile (Median):", p)  # 30

50th Percentile (Median): 20.0


---

## 5️⃣ `np.flip()` – Reverse Array Contents

### 🔹 np.flip()

Flips array elements (like reversing).


In [12]:
arr = np.array([1, 2, 3, 4])
print(np.flip(arr))  # [4 3 2 1]

[4 3 2 1]


---

## 6️⃣ Set Operations in NumPy

### 🔹 np.unique()

Removes duplicates and returns sorted unique values.

In [19]:
arr = np.array([1, 2, 2, 3, 4, 4])
print(np.unique(arr))  # [1 2 3 4]

[1 2 3 4]


### 🔹np.intersect1d() – Common Elements

In [20]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print("Intersection:", np.intersect1d(a, b))

Intersection: [2 3]


### 🔹 np.union1d() – All Unique Elements from Both

In [21]:
print("Union:", np.union1d(a, b))

Union: [1 2 3 4]


### 🔹 np.setdiff1d() – Elements in A but not in B

In [22]:
print("A - B:", np.setdiff1d(a, b))

A - B: [1]


### 🔹 np.setxor1d() – Elements in A or B but not in both

In [23]:
print("Symmetric Difference:", np.setxor1d(a, b))

Symmetric Difference: [1 4]
